---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:24:50.961898Z
# by system_2750@soumyars.com
sites v4.5:
  AHMADABAD_SITE:
    address:
      city: Ahmadabad
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;BGSOUND SRC="javascript:alert(''XSS'');"&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 23.030099868774414
      longitude: 72.58000183105469
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
