---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:24:30.367643Z
# by system_2750@soumyars.com
sites v4.5:
  ALIGARH_SITE:
    address:
      city: Aligarh
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;BODY onload!#$%&()*~+-_.,:;?@[/|\]^`=alert("XSS")&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 27.892200469970703
      longitude: 78.06179809570312
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
