---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:26:45.034098Z
# by system_2750@soumyars.com
sites v4.5:
  BELGAUM_SITE:
    address:
      city: Belgaum
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;A HREF="http://66.102.7.147/"&gt;XSS&lt;/A&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 15.864999771118164
      longitude: 74.50499725341797
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
