---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:24:06.495551Z
# by system_2750@soumyars.com
sites v4.5:
  BHIWANDI_SITE:
    address:
      city: Bhiwandi
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;SCRIPT SRC=http://ha.ckers.org/xss.js'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 19.350000381469727
      longitude: 73.12999725341797
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
