---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:24:15.779546Z
# by system_2750@soumyars.com
sites v4.5:
  BIKANER_SITE:
    address:
      city: Bikaner
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;A HREF="http://66.000146.0x7.147/"&gt;XSS&lt;/A&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 28.030399322509766
      longitude: 73.32990264892578
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
