---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:24:17.684922Z
# by system_2750@soumyars.com
sites v4.5:
  BILASPUR_SITE:
    address:
      city: Bilaspur
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;A HREF="http://ha.ckers.org@google"&gt;XSS&lt;/A&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 22.09040069580078
      longitude: 82.16000366210938
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
