---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:25:18.674298Z
# by system_2750@soumyars.com
sites v4.5:
  CAWNPORE_SITE:
    address:
      city: Cawnpore
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;DIV STYLE="width: expression(alert(''XSS''));"&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 26.459999084472656
      longitude: 80.31999969482422
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
