---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:26:46.675038Z
# by system_2750@soumyars.com
sites v4.5:
  CHANDIGARH_SITE:
    address:
      city: Chandigarh
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;SCRIPT SRC="http://ha.ckers.org/xss.jpg"&gt;&lt;/SCRIPT&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 30.719999313354492
      longitude: 76.77999877929688
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
