---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:25:46.139329Z
# by system_2750@soumyars.com
sites v4.5:
  CHANDA_SITE:
    address:
      city: Chanda
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;A HREF="http://1113982867/"&gt;XSS&lt;/A&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 19.969999313354492
      longitude: 79.30000305175781
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
