---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:26:05.913288Z
# by system_2750@soumyars.com
# FROM_CLOUDBLADE
sites v4.5:
  DEHRA DUN_SITE:
    address:
      city: Dehra Dun
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;SCRIPT&gt;a=/XSS/alert(a.source)&lt;/SCRIPT&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 30.32040023803711
      longitude: 78.05000305175781
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
