---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:25:33.759196Z
# by system_2750@soumyars.com
sites v4.5:
  DHANBAD_SITE:
    address:
      city: Dhanbad
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;XSS STYLE="xss:expression(alert(''XSS''))"&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 23.800399780273438
      longitude: 86.41999816894531
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
