---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:25:37.524860Z
# by system_2750@soumyars.com
sites v4.5:
  INDORE_SITE:
    address:
      city: Indore
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;IMG DYNSRC="javascript:alert(''XSS'');"&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 22.715099334716797
      longitude: 75.86499786376953
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
