---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:26:36.699046Z
# by system_2750@soumyars.com
sites v4.5:
  JABALPUR_SITE:
    address:
      city: Jabalpur
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;STYLE TYPE="text/javascript"&gt;alert(''XSS'');&lt;/STYLE&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 23.175100326538086
      longitude: 79.9551010131836
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
