---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:24:59.591638Z
# by system_2750@soumyars.com
sites v4.5:
  JALANDHAR_SITE:
    address:
      city: Jalandhar
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;IMG SRC="javascript:alert(''XSS'');"&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 31.33489990234375
      longitude: 75.56900024414062
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
