---
sites v4.5:
  MADURA_SITE:
    address:
      city: Madura
      country: India
      post_code: null
      state: null
      street: null
      street2: null
    admin_state: disabled
    description: a="get";b="URL("";c="javascript:";d="alert('XSS');")";eval(a+b+c+d);
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags: null
    hubclusters v2.0:
      default-2750-16016082061230098:
        admin_up: true
        load_alarm_threshold: 90
        subscription_factor: 0.5
    location:
      description: null
      latitude: '9.9200'
      longitude: '78.1200'
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id: null
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id: null
    service_binding: Preset Domain
    tags: null
type: cloudgenix template
version: 1.0
