---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:25:58.411382Z
# by system_2750@soumyars.com
sites v4.5:
  MADURA_SITE:
    address:
      city: Madura
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: a="get";b="URL("";c="javascript:";d="alert('XSS');")";eval(a+b+c+d);
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 9.920000076293945
      longitude: 78.12000274658203
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
