---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:25:29.436413Z
# by system_2750@soumyars.com
sites v4.5:
  MANGALORE_SITE:
    address:
      city: Mangalore
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;IFRAME SRC=http://ha.ckers.org/scriptlet.html &lt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 12.899999618530273
      longitude: 74.8499984741211
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
