---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:26:50.759020Z
# by system_2750@soumyars.com
sites v4.5:
  MUMBAI_SITE:
    address:
      city: Mumbai
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: ''';!--"&lt;XSS&gt;=&{()}'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 19.017000198364258
      longitude: 72.85700225830078
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
