---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:24:46.995722Z
# by system_2750@soumyars.com
sites v4.5:
  NANDED_SITE:
    address:
      city: Nanded
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;SCRIPT a="&gt;''&gt;" SRC="http://ha.ckers.org/xss.js"&gt;&lt;/SCRIPT&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 19.170000076293945
      longitude: 77.30000305175781
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
