---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:26:29.537747Z
# by system_2750@soumyars.com
sites v4.5:
  NELLORE_SITE:
    address:
      city: Nellore
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;SCRIPT ="blah" SRC="http://ha.ckers.org/xss.js"&gt;&lt;/SCRIPT&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 14.4399995803833
      longitude: 79.98989868164062
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
