---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:26:31.516646Z
# by system_2750@soumyars.com
# FROM_CLOUDBLADE
sites v4.5:
  NEW DELHI_SITE:
    address:
      city: New Delhi
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;!--[if gte IE 4]&gt;&lt;SCRIPT&gt;alert(''XSS'');&lt;/SCRIPT&gt;&lt;![endif]--&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 28.600000381469727
      longitude: 77.19999694824219
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
