---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:24:49.167787Z
# by system_2750@soumyars.com
sites v4.5:
  PATNA_SITE:
    address:
      city: Patna
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;IMG SRC=javascript:alert(''XSS'')&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 25.625
      longitude: 85.12999725341797
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
