---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:26:21.280968Z
# by system_2750@soumyars.com
sites v4.5:
  PUNE_SITE:
    address:
      city: Pune
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;BODY ONLOAD=alert(''XSS'')&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 18.530000686645508
      longitude: 73.8499984741211
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
