---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:25:11.446673Z
# by system_2750@soumyars.com
sites v4.5:
  RAJKOT_SITE:
    address:
      city: Rajkot
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;IMG STYLE="xss:expr/*XSS*/ession(alert(''XSS''))"&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 22.309999465942383
      longitude: 70.80000305175781
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
