---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:24:41.791413Z
# by system_2750@soumyars.com
sites v4.5:
  SALEM_SITE:
    address:
      city: Salem
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;STYLE&gt;@import''javascript:alert("XSS")'';&lt;/STYLE&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 11.670000076293945
      longitude: 78.18009948730469
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
