---
sites v4.5:
  <A HREF="http://%77%77%77%2E%67%6F%6F%67%6C%65%2E%63%6F%6D">XSS</A>_SITE:
    address:
      city: Sangli
      country: India
      post_code: null
      state: null
      street: null
      street2: null
    admin_state: disabled
    description: <A HREF="http://%77%77%77%2E%67%6F%6F%67%6C%65%2E%63%6F%6D">XSS</A>
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags: null
    hubclusters v2.0:
      default-2750-16016082061230098:
        admin_up: true
        load_alarm_threshold: 90
        subscription_factor: 0.5
    location:
      description: null
      latitude: '16.8604'
      longitude: '74.5750'
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id: null
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id: null
    service_binding: Preset Domain
    tags: null
type: cloudgenix template
version: 1.0
