---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:25:39.311620Z
# by system_2750@soumyars.com
sites v4.5:
  SOLAPUR_SITE:
    address:
      city: Solapur
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;TABLE BACKGROUND="javascript:alert(''XSS'')"&gt;&lt;/TABLE&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 17.670400619506836
      longitude: 75.9000015258789
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
