---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:25:25.175161Z
# by system_2750@soumyars.com
sites v4.5:
  SRINAGAR_SITE:
    address:
      city: Srinagar
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;LINK REL="stylesheet" HREF="http://ha.ckers.org/xss.css"&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 34.099998474121094
      longitude: 74.81500244140625
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
