---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:24:21.696416Z
# by system_2750@soumyars.com
sites v4.5:
  TINNEVELLY_SITE:
    address:
      city: Tinnevelly
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;A HREF="http://google:ha.ckers.org"&gt;XSS&lt;/A&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 8.730400085449219
      longitude: 77.69000244140625
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
