---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:26:33.188297Z
# by system_2750@soumyars.com
sites v4.5:
  TRICHINOPOLY_SITE:
    address:
      city: Trichinopoly
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;IMG SRC=`javascript:alert("RSnake says, ''XSS''")`&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 10.8100004196167
      longitude: 78.69000244140625
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
