---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:26:27.886618Z
# by system_2750@soumyars.com
sites v4.5:
  UJJAIN_SITE:
    address:
      city: Ujjain
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;A HREF="javascript:document.location=''http://www.google.com/''"&gt;XSS&lt;/A&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 23.190399169921875
      longitude: 75.79000091552734
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
