---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:25:16.684155Z
# by system_2750@soumyars.com
sites v4.5:
  AGRA_SITE:
    address:
      city: Agra
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;STYLE&gt;li {list-style-image: url("javascript:alert(''XSS'')");}&lt;/STYLE&gt;&lt;UL&gt;&lt;LI&gt;XSS'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 27.170400619506836
      longitude: 78.01499938964844
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
