---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:25:07.003509Z
# by system_2750@soumyars.com
sites v4.5:
  AJMER_SITE:
    address:
      city: Ajmer
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;A HREF="http://0x42.0x0000066.0x7.0x93/"&gt;XSS&lt;/A&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 26.450000762939453
      longitude: 74.63999938964844
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
