---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:25:51.848728Z
# by system_2750@soumyars.com
sites v4.5:
  AMRITSAR_SITE:
    address:
      city: Amritsar
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;STYLE&gt;.XSS{background-image:url("javascript:alert(''XSS'')");}&lt;/STYLE&gt;&lt;A
      CLASS=XSS&gt;&lt;/A&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 31.639999389648438
      longitude: 74.87000274658203
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
