---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:24:43.436006Z
# by system_2750@soumyars.com
sites v4.5:
  ASANSOL_SITE:
    address:
      city: Asansol
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;OBJECT TYPE="text/x-scriptlet" DATA="http://ha.ckers.org/scriptlet.html"&gt;&lt;/OBJECT&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 23.683300018310547
      longitude: 86.9832992553711
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
