---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:25:40.961675Z
# by system_2750@soumyars.com
sites v4.5:
  AURANGABAD_SITE:
    address:
      city: Aurangabad
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;META HTTP-EQUIV="Link" Content="&lt;http://ha.ckers.org/xss.css&gt;;
      REL=stylesheet"&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 19.895700454711914
      longitude: 75.32029724121094
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
