---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:24:56.260540Z
# by system_2750@soumyars.com
sites v4.5:
  BENGALURU_SITE:
    address:
      city: Bengaluru
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;SCRIPT&gt;alert(String.fromCharCode(88,83,83))&lt;/SCRIPT&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 12.970000267028809
      longitude: 77.55999755859375
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
