---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:26:00.346563Z
# by system_2750@soumyars.com
sites v4.5:
  COIMBATORE_SITE:
    address:
      city: Coimbatore
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: Redirect 302 /a.jpg http://victimsite.com/admin.asp&deleteuser
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 11.0
      longitude: 76.94999694824219
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
