---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:26:52.576663Z
# by system_2750@soumyars.com
sites v4.5:
  DAVANGERE_SITE:
    address:
      city: Davangere
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;A HREF="http://www.gohttp://www.google.com/ogle.com/"&gt;XSS&lt;/A&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 14.470000267028809
      longitude: 75.91999816894531
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
