---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:24:25.054150Z
# by system_2750@soumyars.com
sites v4.5:
  GORAKHPUR_SITE:
    address:
      city: Gorakhpur
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;SCRIPT a="blah" '''' SRC="http://ha.ckers.org/xss.js"&gt;&lt;/SCRIPT&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 26.75040054321289
      longitude: 83.37999725341797
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
