---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:26:34.858976Z
# by system_2750@soumyars.com
sites v4.5:
  GUNTUR_SITE:
    address:
      city: Guntur
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;A HREF="http://google.com/"&gt;XSS&lt;/A&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 16.329999923706055
      longitude: 80.44999694824219
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
