---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:26:54.111452Z
# by system_2750@soumyars.com
sites v4.5:
  HAORA_SITE:
    address:
      city: Haora
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;BODY BACKGROUND="javascript:alert(''XSS'');"&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 22.580400466918945
      longitude: 88.32990264892578
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
