---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:25:15.019305Z
# by system_2750@soumyars.com
sites v4.5:
  HUBLI_SITE:
    address:
      city: Hubli
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;IMG SRC=javascript:alert(String.fromCharCode(88,83,83))&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 15.359999656677246
      longitude: 75.125
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
