---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:26:38.325863Z
# by system_2750@soumyars.com
sites v4.5:
  JAIPUR_SITE:
    address:
      city: Jaipur
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;FRAMESET&gt;&lt;FRAME SRC="javascript:alert(''XSS'');"&gt;&lt;/FRAMESET&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 26.921100616455078
      longitude: 75.80999755859375
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
