---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:24:11.975169Z
# by system_2750@soumyars.com
sites v4.5:
  JAMMU_SITE:
    address:
      city: Jammu
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;SCRIPT SRC=//ha.ckers.org/.j&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 32.71179962158203
      longitude: 74.8467025756836
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
