---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:25:21.889561Z
# by system_2750@soumyars.com
sites v4.5:
  JAMSHEDPUR_SITE:
    address:
      city: Jamshedpur
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;EMBED SRC="http://ha.ckers.org/xss.swf" AllowScriptAccess="always"&gt;&lt;/EMBED&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 22.787500381469727
      longitude: 86.19750213623047
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
