---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:24:31.879604Z
# by system_2750@soumyars.com
sites v4.5:
  JHANSI_SITE:
    address:
      city: Jhansi
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: perl -e 'print "&&lt;SCRIPT&gt;alert("XSS")&lt;/SCRIPT&gt;";' &gt;
      out
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 25.452999114990234
      longitude: 78.55750274658203
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
