---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:24:52.945363Z
# by system_2750@soumyars.com
sites v4.5:
  KALYAN_SITE:
    address:
      city: Kalyan
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;IMG SRC=''vbscript:msgbox("XSS")''&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 19.250200271606445
      longitude: 73.16020202636719
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
