---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:24:38.532148Z
# by system_2750@soumyars.com
sites v4.5:
  KOCHI_SITE:
    address:
      city: Kochi
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;IMG SRC="livescript:[code]"&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 10.015000343322754
      longitude: 76.2238998413086
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
