---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:25:03.464904Z
# by system_2750@soumyars.com
sites v4.5:
  KOLHAPUR_SITE:
    address:
      city: Kolhapur
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;&lt;SCRIPT&gt;alert("XSS");//&lt;&lt;/SCRIPT&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 16.700000762939453
      longitude: 74.22000122070312
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
