---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:26:57.351738Z
# by system_2750@soumyars.com
sites v4.5:
  KOLKATA_SITE:
    address:
      city: Kolkata
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;SCRIPT&gt;alert(''XSS'')&lt;/SCRIPT&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 22.4950008392334
      longitude: 88.32469940185547
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
