---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:25:32.088315Z
# by system_2750@soumyars.com
sites v4.5:
  KOTA_SITE:
    address:
      city: Kota
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: perl -e 'print "&lt;IMG SRC=javascript:alert("XSS")&gt;";'&gt; out
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 25.18000030517578
      longitude: 75.83499908447266
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
