---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:24:26.680551Z
# by system_2750@soumyars.com
sites v4.5:
  LUCKNOW_SITE:
    address:
      city: Lucknow
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;IFRAME SRC="javascript:alert(''XSS'');"&gt;&lt;/IFRAME&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 26.854999542236328
      longitude: 80.91500091552734
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
