---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:25:55.147666Z
# by system_2750@soumyars.com
sites v4.5:
  LUDHIANA_SITE:
    address:
      city: Ludhiana
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: exp/*&lt;XSS STYLE='no\xss:noxss("*//*");xss:ex/*XSS*//*/*/pression(alert("XSS"))'&gt;
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 30.927799224853516
      longitude: 75.87229919433594
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
