---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:25:01.662881Z
# by system_2750@soumyars.com
sites v4.5:
  MEERUT_SITE:
    address:
      city: Meerut
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;META HTTP-EQUIV="refresh" CONTENT="0;url=javascript:alert(''XSS'');"&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 29.00040054321289
      longitude: 77.69999694824219
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
