---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:26:08.383996Z
# by system_2750@soumyars.com
sites v4.5:
  NAGPUR_SITE:
    address:
      city: Nagpur
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;INPUT TYPE="IMAGE" SRC="javascript:alert(''XSS'');"&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 21.170000076293945
      longitude: 79.08999633789062
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
