---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:26:39.987609Z
# by system_2750@soumyars.com
sites v4.5:
  RAIPUR_SITE:
    address:
      city: Raipur
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;/TITLE&gt;&lt;SCRIPT&gt;alert("XSS");&lt;/SCRIPT&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 21.235000610351562
      longitude: 81.63500213623047
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
