---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:24:54.546679Z
# by system_2750@soumyars.com
sites v4.5:
  RANCHI_SITE:
    address:
      city: Ranchi
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;TABLE&gt;&lt;TD BACKGROUND="javascript:alert(''XSS'')"&gt;&lt;/TD&gt;&lt;/TABLE&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 23.3700008392334
      longitude: 85.33000183105469
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
