---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:24:23.362439Z
# by system_2750@soumyars.com
sites v4.5:
  SANGLI_SITE:
    address:
      city: Sangli
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;A HREF="http://%77%77%77%2E%67%6F%6F%67%6C%65%2E%63%6F%6D"&gt;XSS&lt;/A&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 16.86039924621582
      longitude: 74.57499694824219
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
