---
type: cloudgenix template
version: 1.0
# Created at 2020-10-05T12:24:10.092279Z
# by system_2750@soumyars.com
sites v4.5:
  VISHAKHAPATNAM_SITE:
    address:
      city: Vishakhapatnam
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: '&lt;LAYER SRC="http://ha.ckers.org/scriptlet.html"&gt;&lt;/LAYER&gt;'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 17.729999542236328
      longitude: 83.30500030517578
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
