---
type: cloudgenix template
version: 1.0
# Created at 2020-08-28T01:49:45.847769Z
# by system_5001@cyberdyne.com
sites v4.5:
  SITE_MELBOURNE:
    address:
      city: Melbourne
      country: Australia
      post_code: '32902'
      state: Victoria
      street:
      street2:
    admin_state: disabled
    description: testing Melbourne for MT
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: -37.84093475341797
      longitude: 144.9464569091797
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
