---
type: cloudgenix template
version: 1.0
# Created at 2020-10-03T03:05:43.841309Z
# by system_2750@soumyars.com
sites v4.5:
  BHATPARA_SITE:
    address:
      city: Bhatpara
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: 'this Spoke for site : Bhatpara'
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 22.850400924682617
      longitude: 88.5199966430664
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
    waninterfaces v2.5:
      Circuit to At&T:
        bfd_mode: aggressive
        bw_config_mode: manual
        bwc_enabled: true
        cost: 128
        description:
        label_id: MPLS
        link_bw_down: 30.0
        link_bw_up: 10.0
        lqm_config:
        lqm_enabled: true
        network_id: At&T
        network_type: privatewan
        tags:
        type: privatewan
        vpnlink_configuration:
      Circuit to BSNL:
        bfd_mode: aggressive
        bw_config_mode: manual
        bwc_enabled: true
        cost: 128
        description:
        label_id: Internet DSL
        link_bw_down: 30.0
        link_bw_up: 10.0
        lqm_config:
        lqm_enabled: true
        network_id: BSNL
        network_type: publicwan
        tags:
        type: publicwan
        vpnlink_configuration:
