---
type: cloudgenix template
version: 1.0
# Created at 2020-09-25T12:30:32.828692Z
# by system_2750@soumyars.com
sites v4.5:
  Site_NewYork:
    address:
      city: New York
      country: USA
      post_code: '10001'
      state: USA
      street:
      street2:
    admin_state: active
    description: Test site
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 40.73060989379883
      longitude: -73.93524169921875
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
