---
type: cloudgenix template
version: 1.0
# Created at 2020-09-25T11:39:05.381216Z
# by system_2750@soumyars.com
sites v4.5:
  Site_Melbourne:
    address:
      city: Melbourne
      country: Australia
      post_code: '32902'
      state: Victoria
      street:
      street2:
    admin_state: disabled
    description: EVENT_s1_5001_1_19
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: -37.84093475341797
      longitude: 144.9464569091797
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
