---
type: cloudgenix template
version: 1.0
# Created at 2021-01-04T11:45:16.819012Z
# by system_100@cyberdyne.com
sites v4.5:
  Bangalore:
    address:
      city: Bengaluru
      country: India
      post_code: '56010367'
      state: Karnataka
      street: test12345
      street2: thisistryupdatedbyCLoudblad
    admin_state: active
    description: BangalorelocationupdatedbyCloudBlade
    dhcpservers v2.1:
    - broadcast_address: 192.168.150.255
      custom_options:
      default_lease_time: 43200
      description:
      disabled: false
      dns_servers:
      - 8.8.8.8
      domain_name:
      gateway: 192.168.150.1
      ip_ranges:
      - end_ip: 192.168.150.220
        start_ip: 192.168.150.100
      max_lease_time: 86400
      network_context_id:
      static_mappings:
      subnet: 192.168.150.0/24
      tags:
    element_cluster_role: SPOKE
    elements v2.3:
      ION-SPOKE-3k:
        admin_action:
        allowed_roles:
        - SPOKE
        cluster_insertion_mode:
        cluster_member_id:
        connected: true
        deployment_op:
        description: shiva-vm
        element_security_zones v2.0: []
        interfaces v4.9:
          '1':
            admin_up: true
            attached_lan_networks:
            bound_interfaces:
            bypass_pair:
            description:
            devicemgmt_policysetstack_id:
            dhcp_relay:
            directed_broadcast: false
            ethernet_port:
              full_duplex: false
              speed: 0
            ipv4_config:
              dhcp_config:
              dns_v4_config:
              routes:
              static_config:
              type: dhcp
            mac_address:
            mtu: 1500
            nat_address:
            nat_pools:
            nat_port: 0
            nat_zone_id: internet
            network_context_id:
            parent:
            pppoe_config:
            scope: local
            service_link_config:
            site_wan_interface_ids:
            - Circuit to AIRTEL-boradband-network1
            sub_interface:
            tags:
            type: port
            used_for: public
          '2':
            admin_up: true
            attached_lan_networks:
            bound_interfaces:
            bypass_pair:
            description:
            devicemgmt_policysetstack_id:
            dhcp_relay:
            directed_broadcast: false
            ethernet_port:
              full_duplex: false
              speed: 0
            ipv4_config:
              dhcp_config:
              dns_v4_config:
                name_servers:
                - 8.8.8.8
              routes:
              static_config:
                address: 192.168.150.1/24
              type: static
            mac_address:
            mtu: 1500
            nat_address:
            nat_pools:
            nat_port: 0
            nat_zone_id:
            network_context_id:
            parent:
            pppoe_config:
            scope: local
            service_link_config:
            site_wan_interface_ids:
            sub_interface:
            tags:
            type: port
            used_for: lan
          '3':
            admin_up: true
            attached_lan_networks:
            bound_interfaces:
            bypass_pair:
            description: ''
            devicemgmt_policysetstack_id:
            dhcp_relay:
            directed_broadcast: false
            ethernet_port:
              full_duplex: false
              speed: 0
            ipv4_config:
              dhcp_config:
              dns_v4_config:
              routes:
              static_config:
              type: dhcp
            mac_address:
            mtu: 1500
            nat_address:
            nat_pools:
            nat_port: 0
            nat_zone_id:
            network_context_id:
            parent:
            pppoe_config:
            scope: local
            service_link_config:
            site_wan_interface_ids:
            sub_interface:
            tags:
            type: port
            used_for: public
          '4':
            admin_up: true
            attached_lan_networks:
            bound_interfaces:
            bypass_pair:
            description: ''
            devicemgmt_policysetstack_id:
            dhcp_relay:
            directed_broadcast: false
            ethernet_port:
              full_duplex: false
              speed: 0
            ipv4_config:
              dhcp_config:
              dns_v4_config:
              routes:
              static_config:
              type: dhcp
            mac_address:
            mtu: 1500
            nat_address:
            nat_pools:
            nat_port: 0
            nat_zone_id:
            network_context_id:
            parent:
            pppoe_config:
            scope: local
            service_link_config:
            site_wan_interface_ids:
            sub_interface:
            tags:
            type: port
            used_for: public
          '5.1001':
            admin_up: true
            attached_lan_networks:
            bound_interfaces:
            bypass_pair:
            description:
            devicemgmt_policysetstack_id:
            dhcp_relay:
            directed_broadcast: false
            ethernet_port:
              full_duplex: false
              speed: 0
            ipv4_config:
            mac_address:
            mtu: 0
            nat_address:
            nat_pools:
            nat_port: 0
            nat_zone_id:
            network_context_id:
            parent: '5'
            pppoe_config:
            scope: local
            service_link_config:
            site_wan_interface_ids:
            sub_interface:
              native_vlan: false
              vlan_id: 1001
            tags:
            type: subinterface
            used_for: none
          '6':
            admin_up: true
            attached_lan_networks:
            bound_interfaces:
            bypass_pair:
            description: ''
            devicemgmt_policysetstack_id:
            dhcp_relay:
            directed_broadcast: false
            ethernet_port:
              full_duplex: false
              speed: 0
            ipv4_config:
            mac_address:
            mtu: 1500
            nat_address:
            nat_pools:
            nat_port: 0
            nat_zone_id:
            network_context_id:
            parent:
            pppoe_config:
            scope: local
            service_link_config:
            site_wan_interface_ids:
            sub_interface:
            tags:
            type: port
            used_for: none
          controller 1:
            admin_up: true
            attached_lan_networks:
            bound_interfaces:
            bypass_pair:
            description: ''
            devicemgmt_policysetstack_id:
            dhcp_relay:
            directed_broadcast: false
            ethernet_port:
              full_duplex: false
              speed: 0
            ipv4_config:
              dhcp_config:
              dns_v4_config:
              routes:
              static_config:
              type: dhcp
            mac_address:
            mtu: 1500
            nat_address:
            nat_pools:
            nat_port: 0
            nat_zone_id:
            network_context_id:
            parent:
            pppoe_config:
            scope: local
            service_link_config:
            site_wan_interface_ids:
            sub_interface:
            tags:
            type: port
            used_for: none
        l3_direct_private_wan_forwarding: true
        l3_lan_forwarding: true
        model_name: ion 3000v
        nat_policysetstack_id:
        network_policysetstack_id:
        ntp v2.0:
        - description: Default NTP template created by super user.
          name: default
          ntp_servers:
          - host: 0.cloudgenix.pool.ntp.org
            max_poll: 10
            min_poll: 9
            version: 4
          - host: 1.cloudgenix.pool.ntp.org
            max_poll: 10
            min_poll: 9
            version: 4
          - host: 2.cloudgenix.pool.ntp.org
            max_poll: 10
            min_poll: 9
            version: 4
          - host: 3.cloudgenix.pool.ntp.org
            max_poll: 10
            min_poll: 9
            version: 4
          - host: time.nist.gov
            max_poll: 15
            min_poll: 13
            version: 4
          source_interface_ids:
          tags:
        priority_policysetstack_id:
        role: SPOKE
        routing:
          bgp:
            global_config v2.2:
              admin_distance: 20
              adv_interval: 1
              graceful_restart: false
              hold_time: 90
              keepalive_time: 30
              local_as_num:
              maximum_paths: 1
              md5_secret:
              multi_hop_limit: 1
              peer_auth_type: none
              peer_retry_time: 120
              prefix_adv_type:
              prefix_adv_type_to_lan: default
              prefixes_to_adv_to_wan:
              router_id:
              stalepath_time: 120
          static v2.0: []
        serial_number: a28d1542-f610-abd1-c741-97a1cd6d0045
        software_version: 5.4.3-b9
        spoke_ha_config:
        state: bound
        tags:
        tenant_id: '100'
        toolkit v2.2:
          account_disable_interval: 5
          inactive_interval: 15
          otpkey_version: 1
          retry_login_count: 5
          ssh_enabled: true
          ssh_outbound_enabled: true
        vpn_to_vpn_forwarding: false
    extended_tags:
    location:
      description:
      latitude: 12.8635892868042
      longitude: 77.65642547607422
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
    waninterfaces v2.6:
      Circuit to AIRTEL-boradband-network1:
        bfd_mode: aggressive
        bw_config_mode: manual
        bwc_enabled: true
        cost: 128
        description:
        label_id: Ethernet Internet
        link_bw_down: 30.0
        link_bw_up: 10.0
        lqm_config:
        lqm_enabled: true
        network_id: AIRTEL-boradband-network1
        network_type: publicwan
        tags:
        type: publicwan
        use_for_application_reachability_probes:
        use_for_controller_connections:
        vpnlink_configuration:
